import { z } from "zod";
import * as fs from "fs";
import * as path from "path";
import { loadRoutingConfig, resolveRouting } from "./loadRouting";

// ── Selector config (custom-playwright only) ──────────────────────────────────

export const SelectorsSchema = z.object({
  jobCard:         z.string(),
  title:           z.string(),
  location:        z.string().optional(),
  applyUrl:        z.string(),
  postedDate:      z.string().optional(),
  postedDateAttr:  z.string().optional(),   // attribute to read date from (e.g. "datetime")
  scrollToLoad:    z.boolean().optional(),
  waitForSelector: z.string().optional(),
  timeoutMs:       z.number().optional(),
});

// ── Company config (internal representation) ──────────────────────────────────

export const ATS_VALUES = [
  "greenhouse",
  "lever",
  "ashby",
  "workday",
  "smartrecruiters",
  "workable",
  "bamboohr",
  "amazon",
  "google-playwright",
  "meta-playwright",
  "custom-playwright",
  "manual",
] as const;

export type AtsValue = typeof ATS_VALUES[number];

export const CompanyConfigSchema = z.object({
  /** Deterministic UUID from the external targets JSON (uuidv5 from slug). */
  id:             z.string().optional(),
  name:           z.string().min(1),
  ats:            z.enum(ATS_VALUES),
  slug:           z.string().nullable(),
  careersUrl:     z.string().url(),
  roles:          z.array(z.string()).default([]),
  enabled:        z.boolean().default(true),
  earlyCareerUrl: z.string().url().optional(),
  selectors:      SelectorsSchema.optional(),
}).refine(
  (c) => c.ats !== "custom-playwright" || c.selectors !== undefined,
  { message: "selectors is required when ats is 'custom-playwright'" },
);

// ── Defaults ──────────────────────────────────────────────────────────────────

export const DefaultsSchema = z.object({
  maxExperienceYears: z.number().default(3),
  locationFilter:     z.string().default("US"),
  dateCutoffDays:     z.number().default(30),
});

// ── Internal targets format ───────────────────────────────────────────────────

export const TargetsConfigSchema = z.object({
  version:   z.literal(1),
  defaults:  DefaultsSchema,
  companies: z.array(CompanyConfigSchema),
});

export type SelectorsConfig = z.infer<typeof SelectorsSchema>;
export type CompanyConfig   = z.infer<typeof CompanyConfigSchema>;
export type TargetsConfig   = z.infer<typeof TargetsConfigSchema>;

// ── External targets format (config/targets.json generated by user) ───────────
// This schema is flexible — we only validate the parts we actually read.

const ExternalCompanySchema = z.object({
  uuid:               z.string().optional(),
  slug:               z.string(),
  name:               z.string(),
  category:           z.string().optional(),
  careers_url:        z.string(),
  program_url:        z.string().nullable().optional(),
  has_apm_program:    z.boolean().optional(),
  apm_program_name:   z.string().nullable().optional(),
  apm_program_status: z.string().nullable().optional(),
  domain_tags:        z.array(z.string()).optional(),
  target_roles:       z.array(z.string()).optional(),
  notes:              z.string().nullable().optional(),
  index:              z.number().optional(),
  content_hash:       z.string().optional(),
  // Optional ATS override — if the user adds this field to a company entry
  ats:                z.string().optional(),
});

const ExternalTargetsConfigSchema = z.object({
  metadata: z.object({
    title:            z.string().optional(),
    version:          z.string().optional(),
    schema_version:   z.string().optional(),
    total_companies:  z.number().optional(),
  }).passthrough().optional(),
  filters: z.object({
    target_roles:            z.array(z.string()).optional(),
    title_include_keywords:  z.array(z.string()).optional(),
    title_exclude_keywords:  z.array(z.string()).optional(),
    experience: z.object({
      max_years:          z.number().optional(),
      reject_above_years: z.number().optional(),
    }).passthrough().optional(),
    freshness: z.object({
      max_posting_age_days: z.number().optional(),
    }).passthrough().optional(),
  }).passthrough().optional(),
  ranking_rules:            z.record(z.unknown()).optional(),
  categories:               z.array(z.string()).optional(),
  company_field_descriptions: z.record(z.string()).optional(),
  companies: z.array(ExternalCompanySchema),
}).passthrough();

type ExternalCompany = z.infer<typeof ExternalCompanySchema>;

// ── ATS detection ─────────────────────────────────────────────────────────────

// Static slug→ATS map built from the hardcoded company list.
// Kept in sync with companies.ts — if you add a new company there,
// add it here too so the external-schema adapter can route it.
const SLUG_TO_ATS: Record<string, AtsValue> = {
  // Greenhouse
  airbnb: "greenhouse", stripe: "greenhouse", coinbase: "greenhouse",
  lyft: "greenhouse", dropbox: "greenhouse", instacart: "greenhouse",
  reddit: "greenhouse", discord: "greenhouse", robinhood: "greenhouse",
  chime: "greenhouse", brex: "greenhouse", anthropic: "greenhouse",
  scaleai: "greenhouse", databricks: "greenhouse", cloudflare: "greenhouse",
  twilio: "greenhouse", amplitude: "greenhouse", pagerduty: "greenhouse",
  datadog: "greenhouse", okta: "greenhouse", affirm: "greenhouse",
  faire: "greenhouse", gusto: "greenhouse", checkr: "greenhouse",
  lattice: "greenhouse", verkada: "greenhouse", airtable: "greenhouse",
  intercom: "greenhouse", asana: "greenhouse", carta: "greenhouse",
  rubrik: "greenhouse", duolingo: "greenhouse", roblox: "greenhouse",
  samsara: "greenhouse", squarespace: "greenhouse", sofi: "greenhouse",
  fivetran: "greenhouse", jfrog: "greenhouse", figma: "greenhouse",
  vercel: "greenhouse", mixpanel: "greenhouse", block: "greenhouse",
  qualtrics: "greenhouse", toast: "greenhouse", attentive: "greenhouse",
  klaviyo: "greenhouse", launchdarkly: "greenhouse", contentful: "greenhouse",
  algolia: "greenhouse", starburst: "greenhouse", netlify: "greenhouse",
  cockroachlabs: "greenhouse", planetscale: "greenhouse", temporal: "greenhouse",
  zscaler: "greenhouse", mongodb: "greenhouse", elastic: "greenhouse",
  wunderkind: "greenhouse", ziprecruiter: "greenhouse", blend: "greenhouse",
  opendoor: "greenhouse", flexport: "greenhouse", coupang: "greenhouse",
  handshake: "greenhouse", remote: "greenhouse", webflow: "greenhouse",
  gitlab: "greenhouse", hubspotjobs: "greenhouse", hubspot: "greenhouse",
  coursera: "greenhouse", udemy: "greenhouse", pendo: "greenhouse",
  smartsheet: "greenhouse", braze: "greenhouse", sendbird: "greenhouse",
  orca: "greenhouse", axonius: "greenhouse", abnormalsecurity: "greenhouse",
  exabeam: "greenhouse", postman: "greenhouse", togetherai: "greenhouse",
  salesloft: "greenhouse", five9: "greenhouse", dialpad: "greenhouse",
  natera: "greenhouse", omadahealth: "greenhouse", lucidsoftware: "greenhouse",
  uber: "greenhouse", doordash: "greenhouse", pinterest: "greenhouse",
  snap: "greenhouse", miro: "greenhouse", box: "greenhouse",
  procore: "greenhouse", rippling: "greenhouse", benchling: "greenhouse",
  waymo: "greenhouse", rivian: "greenhouse", grafana: "greenhouse",
  navan: "greenhouse", harness: "greenhouse", alma: "greenhouse",
  andurilindustries: "greenhouse", anduril: "greenhouse", gleanwork: "greenhouse",
  glean: "greenhouse", headway: "greenhouse", project44: "greenhouse",
  uberfreight: "greenhouse",
  // Lever
  atlassian: "lever", plaid: "lever", outreach: "lever",
  netflix: "lever", palantir: "lever", neon: "lever",
  lucidworks: "lever", mistral: "lever", clari: "lever",
  highspot: "lever", mindtickle: "lever", freshworks: "lever",
  girlswhocode: "lever", wandb: "lever", cohere: "lever",
  "weights-biases": "lever", weightsandbiases: "lever",
  // Ashby
  linear: "ashby", ramp: "ashby", mercury: "ashby",
  retool: "ashby", watershed: "ashby", notion: "ashby",
  descript: "ashby", deel: "ashby", pave: "ashby",
  coda: "ashby", hex: "ashby", tome: "ashby",
  perplexity: "ashby", dbtlabs: "ashby", anyscale: "ashby",
  characterai: "ashby", cedar: "ashby", openai: "ashby",
  snowflake: "ashby",
  // Special scrapers
  amazon: "amazon",
  google: "google-playwright",
  meta: "meta-playwright",
};

/**
 * Try to detect ATS from the careers URL alone.
 * Catches cases where the URL goes directly to an ATS-hosted page.
 */
function detectAtsFromUrl(url: string): AtsValue | null {
  const u = url.toLowerCase();
  if (u.includes("boards.greenhouse.io") || u.includes("greenhouse.io/embed")) return "greenhouse";
  if (u.includes("jobs.lever.co") || u.includes("lever.co/jobs"))               return "lever";
  if (u.includes("ashbyhq.com") || u.includes("app.ashbyhq.com"))               return "ashby";
  if (u.includes("amazon.jobs"))                                                  return "amazon";
  if (u.includes("metacareers.com") || u.includes("facebook.com/careers"))      return "meta-playwright";
  if (u.includes("google.com/about/careers") || u.includes("careers.google.com")) return "google-playwright";
  return null;
}

/**
 * Determine the ATS for an external-format company entry.
 * Priority: explicit ats field → slug lookup → URL detection.
 * Returns null if the ATS cannot be determined.
 */
function resolveAts(ext: ExternalCompany): AtsValue | null {
  // 1. Explicit override in the company entry
  if (ext.ats && ATS_VALUES.includes(ext.ats as AtsValue)) {
    return ext.ats as AtsValue;
  }
  // 2. Slug-based lookup (exact match and normalised variant)
  const slugNorm = ext.slug.toLowerCase().replace(/[^a-z0-9]/g, "");
  if (SLUG_TO_ATS[ext.slug])      return SLUG_TO_ATS[ext.slug];
  if (SLUG_TO_ATS[slugNorm])      return SLUG_TO_ATS[slugNorm];
  // 3. URL-based detection
  return detectAtsFromUrl(ext.careers_url);
}

// ── External-format adapter ───────────────────────────────────────────────────

function adaptExternalConfig(
  ext: z.infer<typeof ExternalTargetsConfigSchema>,
): TargetsConfig {
  const globalRoles: string[] =
    ext.filters?.target_roles ??
    ext.filters?.title_include_keywords ??
    [];

  const maxYears =
    ext.filters?.experience?.reject_above_years ??
    ext.filters?.experience?.max_years ??
    3;

  const dateCutoff =
    ext.filters?.freshness?.max_posting_age_days ??
    30;

  // Load routing config once for all companies (cached after first load).
  let routingFile: ReturnType<typeof loadRoutingConfig> | null = null;
  try {
    routingFile = loadRoutingConfig();
  } catch {
    // ats_routing.json missing — scrapers will fall back to company slug
  }

  const companies: CompanyConfig[] = [];
  let skipped = 0;

  for (const c of ext.companies) {
    const roles =
      c.target_roles && c.target_roles.length > 0 ? c.target_roles : globalRoles;

    // Check raw routing entry first — resolveRouting() returns null for manual,
    // so we must inspect the file directly to distinguish manual from unmapped.
    const slugNormForLookup = c.slug.toLowerCase().replace(/[^a-z0-9]/g, "");
    const rawRoutingEntry = routingFile
      ? (routingFile.routing[c.slug] ??
         Object.entries(routingFile.routing).find(
           ([k]) => k.toLowerCase().replace(/[^a-z0-9]/g, "") === slugNormForLookup,
         )?.[1])
      : undefined;

    // Manual companies: add with ats="manual" so the orchestrator can log them
    // as skipped rather than calling a scraper that will always 404.
    if (rawRoutingEntry?.ats === "manual") {
      companies.push({
        id:         c.uuid,
        name:       c.name,
        ats:        "manual" as AtsValue,
        slug:       c.slug,
        careersUrl: c.careers_url,
        roles,
        enabled:    true,
      });
      continue;
    }

    // ── ATS resolution (3-step priority) ───────────────────────────────────
    // Step 1: routing file has an explicit non-manual entry → authoritative.
    //   This is the primary fix for the 121-company bug: companies that are in
    //   ats_routing.json but NOT in SLUG_TO_ATS were previously silently dropped
    //   because resolveAts() returned null before we ever reached this check.
    let ats: AtsValue | null = null;
    if (rawRoutingEntry && rawRoutingEntry.ats !== "manual" &&
        ATS_VALUES.includes(rawRoutingEntry.ats as AtsValue)) {
      ats = rawRoutingEntry.ats as AtsValue;
    }

    // Step 2: URL-pattern and hardcoded-slug detection (SLUG_TO_ATS map).
    if (!ats) ats = resolveAts(c);

    // Step 3: fall back to routing file's unmapped_default so NO company is
    //   silently dropped. Companies without discovered routing are still
    //   attempted (they'll error with a clear "ATS not yet discovered" message
    //   that shows up in the run stats and email footer).
    if (!ats && routingFile) {
      const def = routingFile.unmapped_default as AtsValue;
      if (ATS_VALUES.includes(def) && def !== "manual") {
        ats = def;
      }
    }

    if (!ats) {
      skipped++;
      continue;
    }

    // ── Build routing entry ─────────────────────────────────────────────────
    // Consult ats_routing.json for board-specific slug/host overrides.
    // - API scrapers (Greenhouse/Lever/Ashby) use `slug` to identify their board.
    // - Workday entries use `host` (no `slug`) — check for either.
    // - Unmapped fallback has neither slug nor host.
    const routingEntry = routingFile ? resolveRouting(c.slug, routingFile) : null;
    const hasExplicitRoute = !!(routingEntry?.slug || routingEntry?.host);
    const effectiveAts: AtsValue =
      hasExplicitRoute && routingEntry!.ats && ATS_VALUES.includes(routingEntry!.ats as AtsValue)
        ? (routingEntry!.ats as AtsValue)
        : ats;
    const atsSlug = routingEntry?.slug ?? c.slug;

    const entry: CompanyConfig = {
      id:         c.uuid,           // preserve UUID for Supabase FK lookups
      name:       c.name,
      ats:        effectiveAts,
      slug:       atsSlug,
      careersUrl: c.careers_url,
      roles,
      enabled:    true,
    };

    // Use program_url as earlyCareerUrl if it looks like a real URL
    if (c.program_url) {
      try {
        new URL(c.program_url);
        entry.earlyCareerUrl = c.program_url;
      } catch { /* not a URL, skip */ }
    }

    // Wire selectors from ats_routing.json for custom-playwright companies.
    // Without this, scrapeCustomPlaywright() throws "ATS not yet discovered"
    // even for companies that discoverATS.js has already mapped with selectors.
    if (effectiveAts === "custom-playwright" && routingEntry?.selectors) {
      entry.selectors = routingEntry.selectors;
      // Some routing entries override the URL (e.g. LinkedIn uses a different
      // URL than the company's careersUrl). Use it so Playwright navigates correctly.
      if (routingEntry.url_override) {
        entry.careersUrl = routingEntry.url_override;
      }
    }

    companies.push(entry);
  }

  if (skipped > 0) {
    console.log(
      `[config] Skipped ${skipped} / ${ext.companies.length} companies` +
      ` — ATS could not be determined (no routing entry, slug match, URL hint, or unmapped_default).` +
      ` Add an "ats" field to those entries or run scripts/discoverATS.js --batch to enable them.`,
    );
  }

  return {
    version: 1,
    defaults: {
      maxExperienceYears: maxYears,
      locationFilter: "US",
      dateCutoffDays: dateCutoff,
    },
    companies,
  };
}

// ── Loader ────────────────────────────────────────────────────────────────────

/**
 * Load and validate the targets config file.
 * Returns null if the file doesn't exist (fallback to hardcoded list).
 * Supports two JSON schemas:
 *   1. Internal format  — { version: 1, defaults, companies }
 *   2. External format  — { metadata, filters, categories, companies } (user-generated)
 * Throws with a descriptive error if the file is present but neither schema matches.
 */
export function loadTargetsConfig(): TargetsConfig | null {
  const configPath =
    process.env.TARGETS_CONFIG_PATH ??
    path.join(process.cwd(), "config", "targets.json");

  if (!fs.existsSync(configPath)) return null;

  let raw: string;
  try {
    raw = fs.readFileSync(configPath, "utf-8");
  } catch (err) {
    throw new Error(
      `[config] Cannot read targets config at ${configPath}: ${err instanceof Error ? err.message : err}`,
    );
  }

  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch {
    throw new Error(
      `[config] targets.json is not valid JSON — check ${configPath}`,
    );
  }

  // ── Try internal format first ─────────────────────────────────────────────
  const internal = TargetsConfigSchema.safeParse(json);
  if (internal.success) {
    const enabled = internal.data.companies.filter((c) => c.enabled).length;
    console.log(
      `[config] Loaded ${internal.data.companies.length} companies ` +
      `(${enabled} enabled) from ${configPath} [internal format]`,
    );
    return internal.data;
  }

  // ── Try external format ───────────────────────────────────────────────────
  const external = ExternalTargetsConfigSchema.safeParse(json);
  if (external.success) {
    const adapted = adaptExternalConfig(external.data);
    const enabled = adapted.companies.filter((c) => c.enabled).length;
    console.log(
      `[config] Loaded ${ext_companyCount(external.data)} companies from ${configPath}` +
      ` [external format] → ${adapted.companies.length} actionable (${enabled} enabled)`,
    );
    return adapted;
  }

  // ── Neither format matched ────────────────────────────────────────────────
  const issues = external.error.issues
    .slice(0, 10)
    .map((i) => `  • ${i.path.join(".")}: ${i.message}`)
    .join("\n");
  throw new Error(
    `[config] targets.json does not match any supported schema at ${configPath}.\n` +
    `Top issues (external format):\n${issues}\n\n` +
    `See config/targets.json.example for the internal format.\n` +
    `For the extended format, ensure the file has a top-level "companies" array.`,
  );
}

function ext_companyCount(ext: z.infer<typeof ExternalTargetsConfigSchema>): number {
  return ext.metadata?.total_companies ?? ext.companies.length;
}
